version: "3.8"

networks:
  internal:
    external: true
  traefik-public:
    external: true
  monitor-net:
    external: true

services:
  traefik:
    image: traefik:v3.6.8
    container_name: traefik
    restart: always
    env_file: ${MNT_CONFIGS}/docker_secrets/traefik/traefik.env
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MNT_CONFIGS}/git/confs/edge/conf/traefik:/etc/traefik
      #- /data/edge/traefik/traefik.log:/traefik.log
      #- /data/edge/traefik/access.log:/access.log
      - /data/edge/traefik/acme.json:/acme.json
      - ${MNT_CONFIGS}/git/confs/edge/conf/traefik/rules:/dynamic
    networks:
      - traefik-public
    # Global mode makes an instance of traefik listen on _every_ node, so that regardless of which
    # node the request arrives on, it'll be forwarded to the correct backend service.
    labels:
      # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      # Use the custom label "traefik.constraint-label=traefik-public"
      - traefik.constraint-label=traefik-public
      # admin-auth middleware with HTTP Basic auth
      # Using the environment variables USERNAME and HASHED_PASSWORD
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
      # https-redirect middleware to redirect HTTP to HTTPS
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.routers.http-catchall.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # traefik-https the actual router using HTTPS
      - traefik.http.routers.traefik-public-https.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.tls=true
      # Use the special Traefik service api@internal with the web UI/Dashboard
      - traefik.http.routers.traefik-public-https.service=api@internal
      # Use the "le" (Let's Encrypt) resolver created below
      - traefik.http.routers.traefik-public-https.tls.certresolver=main
      # Enable HTTP Basic auth, using the middleware created above
      - traefik.http.routers.traefik-public-https.middlewares=admin-auth
      # Define the port inside of the Docker service to use
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080

  argo-tunnel:
    container_name: home-sm-dev-uk
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    networks:
      - internal
      - traefik-public
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  auth-redis:
    image: redis:8.4.0
    container_name: authentik_redis
    command: --save 60 1 --loglevel warning
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - /data/edge/redis:/data
    networks:
      - internal

  auth-server:
    image: ghcr.io/goauthentik/server:2025.12.3
    container_name: authentik_server
    restart: always
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik_redis
      AUTHENTIK_POSTGRESQL__HOST: "${AUTHENTIK_POSTGRESQL_HOST}"
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL_NAME}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL_PASSWORD}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    volumes:
      - /data/edge/authentik/media:/media
      - /data/edge/authentik/custom-templates:/templates
      - /data/edge/geoip:/geoip
    env_file:
      - ${MNT_CONFIGS}/git/confs/edge/conf/authentik/authentik.env
    ports:
      - "0.0.0.0:${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "0.0.0.0:${AUTHENTIK_PORT_HTTPS:-9443}:9443"
    networks:
      - internal
      - traefik-public

  auth-worker:
    image: ghcr.io/goauthentik/server:2025.12.3
    container_name: authentik_worker
    restart: always
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik_redis
      AUTHENTIK_POSTGRESQL__HOST: "${AUTHENTIK_POSTGRESQL_HOST}"
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL_NAME}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL_PASSWORD}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # This is optional, and can be removed. If you remove this, the following will happen
      # - The permissions for the /media folders aren't fixed, so make sure they are 1000:1000
      # - The docker socket can't be accessed anymore
    user: root
    volumes:
      - /data/edge/authentik/media:/media
      - /data/edge/authentik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/edge/authentik/custom-templates:/templates
      - /data/edge/geoip:/geoip
    env_file:
      - ${MNT_CONFIGS}/git/confs/edge/conf/authentik/authentik.env
    networks:
      - internal

  auth-geoipupdate:
    image: maxmindinc/geoipupdate:v7.1
    container_name: authentik_geoip
    restart: always
    volumes:
      - "/data/edge/geoip:/usr/share/GeoIP"
    environment:
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_FREQUENCY: "8"
    env_file:
      - ${MNT_CONFIGS}/git/confs/edge/conf/authentik/authentik.env
    networks:
      - internal

  uptime-kuma:
    image: louislam/uptime-kuma:2.1.0
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
    ports:
      - 3001:3001
    volumes:
      - /data/edge/uptime:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitor-net
      - traefik-public

  web:
    image: nginx:latest
    container_name: web
    volumes:
      - /data/edge/web:/var/www/html
      - ${MNT_CONFIGS}/git/confs/edge/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 42096:80
    networks:
      - traefik-public
    restart: unless-stopped
